import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import { assertIsDefined } from "../helpers/assert";
import styles from "../styles/Home.module.css";

export const getServerSideProps: GetServerSideProps = async () => {
  process.env.SECRET_TOKEN; // string | undefined

  // `process.env.SECRET_TOKEN` should be defined.
  assertIsDefined(process.env.SECRET_TOKEN);

  process.env.SECRET_TOKEN; // string

  console.log("use secret value in [server] side:", process.env.SECRET_TOKEN);

  return { props: {} };
};

const Home: NextPage = () => {
  useEffect(() => {
    console.log("use secret value in [client] side:", process.env.SECRET_TOKEN);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Running in{" "}
          <code className={styles.code}>{process.env.NEXT_PUBLIC_APP_ENV}</code>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
